stages:
  - build

linux-x86_64:
  stage: build
  interruptible: true
  before_script:
    - apk add bash
  script:
    - ./build.sh release-static
  only:
    - release-4..0.1
  artifacts:
    name: linux-x86_64
    paths:
      - /lethean-gui-linux-64bit-4.0.2.tar.bz2


#windows:
#  stage: build
#  interruptible: true
#  before_script:
#    - choco install -y pacman git
#    - refreshenv
#    - pacman -S mingw-w64-i686-toolchain make mingw-w64-i686-cmake mingw-w64-i686-boost
#  script:
#    - ci\run.sh
#  only:
#    - develop-next
#  tags:
#    - shared-windows
#    - windows
#    - windows-1809

