stages:
  - build

Linux:
  image: lthn/build:lthn-wallet-linux
  stage: build
  interruptible: true
  script:
    - bash ci/run.sh
  artifacts:
    expose_as: 'Linux'
    name: lethean-wallet-linux-x86_64
    paths:
      - /home/lthn/wallet/build/release/bin/


#  stage: build
#  interruptible: true
#  before_script:
#    - choco install -y pacman git
#    - refreshenv
#    - pacman -S mingw-w64-i686-toolchain make mingw-w64-i686-cmake mingw-w64-i686-boost
#  script:
#    - ci\run.sh
#  only:
#    - develop-next
#  tags:
#    - shared-windows
#    - windows
#    - windows-1809

