include:
  - template: Auto-DevOps.gitlab-ci.yml

build:
  image: lthn/build:lthn-wallet-linux
  stage: build
  interruptible: true
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - bash ci/run.sh
  artifacts:
    name: linux-x86_64
    paths:
      - /home/lthn/wallet/build/release/bin/

#windows:
#  stage: build
#  interruptible: true
#  before_script:
#    - choco install -y pacman git
#    - refreshenv
#    - pacman -S mingw-w64-i686-toolchain make mingw-w64-i686-cmake mingw-w64-i686-boost
#  script:
#    - ci\run.sh
#  only:
#    - develop-next
#  tags:
#    - shared-windows
#    - windows
#    - windows-1809

